site:
  about:
    siteName: '<span class="titlesup">r</span>k3<span class="titlesup">r</span>n3<span class="titlesup">r</span> d<span class="titlesup">e</span>v'
    subtitle: 'Software Architecture, Data Streaming with Apache Kafka, Java, Kotlin and more'
#    siteDescription: 'This is a short blurb you can set below this index layouts sidebar.'
    avatar: 'assets/images/logo.jpg'
    favicon: 'assets/favicon.ico'

pages:
  staticPages:
    layout: single

posts:
#  permalink: ':category/:year/:monthName/:slug'
  categories:
    - key: 'blog'
      title: 'Blog'
      path: 'blog/'
      permalink: 'blog/:slug'
    - key: 'blog/debezium'
      title: 'Debezium'
      path: 'blog/debezium/'
      permalink: 'blog/:slug'
    - key: 'blog/kafka'
      title: 'Apache Kafka'
      path: 'blog/kafka/'
      permalink: 'blog/:slug'

assets:
  sourceDirs:
    - 'assets/css'
    - 'assets/images'
    - 'assets/fonts'

theme:
  social:
    twitter: rk3rn3r
    github: rk3rn3r
    instagram: rk3rn3r
    other:
      - label: 'XING'
        link: 'https://www.xing.com/profile/Rene_Kerner'
        icon: 'fa-xing'
        order: 0
      - label: 'LinkedIn'
        link: 'https://www.linkedin.com/in/ren%C3%A9-kerner-495019164/'
        icon: 'fa-linkedin-square'
        order: 1

  menu:
#    - type: "wikiSections"
    - type: 'taxonomy'
      taxonomyType: 'categories'
      includeTerms: true
      termsAtRoot: true
    - type: 'page'
      title: 'About Me'
      itemId: 'About Me'
    - type: 'page'
      title: 'Imprint'
      itemId: 'Imprint - Impressum'
    - type: 'page'
      title: 'Privacy Notes'
      itemId: 'Privacy Notes'
#    - type: "pages"
#      atRoot: true

  sidebar:
    - type: recentPosts
      limit: 5
#      category: gallery
      noWrapper: true
      template:
        - 'includes/postPreview_mini'
#    - type: recentPosts
#      limit: 5
#      category: personal
#      noWrapper: true
#      template:
#        - 'includes/postPreview_list'
  extraCss:
    - 'assets/sass/rk3rn3r.scss'

#  extraJs:
#    - 'assets/js/extraJs.js'

#services:
#  render:
#    includeDrafts: true
#  generators:
#    externalIndices:
#      - 'https://orchid.netlify.com/meta/all.index.json'
