site:
  about:
    siteName: '<span class="titlesup">r</span>k3<span class="titlesup">r</span>n3<span class="titlesup">r</span> d<span class="titlesup">e</span>v'
    subtitle: 'Software Architecture, Data Streaming with Apache Kafka, Java, Kotlin and more'
#    siteDescription: 'This is a short blurb you can set below this index layouts sidebar.'
    avatar: '/assets/images/logo.jpg'
    favicon: '/assets/favicon.ico'

posts:
  categories:
    - key: 'blog'
      title: 'Blog'
      path: 'blog/'
      permalink: 'blog/:slug'
    - key: 'blog/debezium'
      title: 'Debezium'
      path: 'blog/debezium'
      permalink: 'blog/:slug'
    - key: 'blog/kafka'
      title: 'Apache Kafka'
      path: 'blog/kafka'
      permalink: 'blog/:slug'

assets:
  sourceDirs:
    - 'assets/css'
    - 'assets/images'
    - 'assets/fonts'

theme:
  social:
    other:
      - label: 'twitter'
        link: 'https://twitter.com/rk3rn3r'
        icon: 'fa-twitter'
        order: 4
      - label: 'GitHub'
        link: 'https://github.com/rk3rn3r'
        icon: 'fa-github'
        order: 3
      - label: 'instagram'
        link: 'https://www.instagram.com/rk3rn3r/'
        icon: 'fa-instagram'
        order: 2
      - label: 'LinkedIn'
        link: 'https://www.linkedin.com/in/ren%C3%A9-kerner-495019164/'
        icon: 'fa-linkedin-square'
        order: 1
      - label: 'XING'
        link: 'https://www.xing.com/profile/Rene_Kerner'
        icon: 'fa-xing'
        order: 0

  menu:
    - type: 'page'
      title: 'Home'
      url: '/'
#    - type: "wikiSections"
    - type: 'taxonomy'
      taxonomyType: 'categories'
      includeTerms: true
      termsAtRoot: true
    - type: 'page'
      title: 'About Me'
      itemId: 'About Me'
    - type: 'page'
      title: 'Imprint'
      itemId: 'Imprint - Impressum'
    - type: 'page'
      title: 'Privacy Notes'
      itemId: 'Privacy Notes'
#    - type: "pages"
#      atRoot: true

  sidebar:
    - type: recentPosts
      limit: 5
#      category: gallery
      noWrapper: true
      template:
        - 'includes/postPreview_mini'
#    - type: recentPosts
#      limit: 5
#      category: personal
#      noWrapper: true
#      template:
#        - 'includes/postPreview_list'
#  extraCss:
#    - 'assets/css/font-awesome.css'
#    - 'assets/css/rk3rn3r.scss'
#    - 'assets/css/pygments.scss'
#  extraJs:
#    - 'assets/js/extraJs.js'

#services:
#  render:
#    includeDrafts: true
#  generators:
#    externalIndices:
#  - 'https://orchid.netlify.com/meta/all.index.json'